services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    env_file:
      - .env  # Charge les variables d'environnement depuis le fichier .env
    environment:
      MONGO_URI: "mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_DATABASE}.mongodb.net/?retryWrites=true&w=majority&appName=GoFastCluster"
    command: air -c .air.toml

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    working_dir: /app
    env_file:
      - .env  # Charge les mêmes variables pour l'environnement dev

volumes:
  go-mod-cache:
