services:
  api:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env  # Charge les variables d'environnement depuis le fichier .env
    environment:
      MONGO_URI: "mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_DATABASE}.mongodb.net/?retryWrites=true&w=majority&appName=GoFastCluster"

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env  # Charge les mêmes variables pour l'environnement dev
