services:
  api:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env # Charge les mêmes variables pour l'environnement dev
