FROM golang:1.22-alpine

WORKDIR /app

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
# Use a specific version of Air compatible with Go 1.22
RUN go install github.com/cosmtrek/air@v1.49.0

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]