name: Lint Go Code

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-lint-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-lint-
      
      - name: Build and cache lint image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.dev
          load: true
          tags: gofast-dev:lint
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      
      - name: Run golangci-lint
        run: docker run --rm -v $(pwd):/app gofast-dev:lint golangci-lint run

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
